#!/usr/bin/env bash
#
# Run all dotfiles installers.

INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && pwd )"
export DOT=$(echo $INSTALL_DIR | sed 's/\/_install//g')

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
